/**
 * Auth helpers for the Word add-in.
 *
 * The add-in cannot run a full OAuth PKCE flow itself (Office blocks the
 * redirect popup pattern, and our Max auth provider — eulex.ai WordPress
 * — issues per-app tokens via PKCE). Instead, the user logs in to the
 * Max web frontend, generates a 6-digit pairing code on the
 * Account → Word add-in page, and types the code here. The backend
 * exchanges that code for the JWT the frontend already holds.
 *
 * The token is stored in localStorage. Office task panes get a per-host
 * storage origin, so this does not leak between users on a shared box —
 * each Windows/macOS account has its own.
 */

const TOKEN_KEY = "mike.token";

declare const process: { env: { API_BASE_URL?: string } };

/**
 * Default API base. In production the add-in is served from the same
 * origin as the frontend (https://mike-frontend.../word-addin/...), and
 * the backend is reachable via the same origin in practice. During local
 * dev the frontend webpack-dev-server runs on https://localhost:3002 and
 * the backend on http://localhost:3001, so we read the override from .env.
 */
function defaultApiBase(): string {
    if (typeof window !== "undefined" && window.location?.origin) {
        return window.location.origin;
    }
    return "http://localhost:3001";
}

export const API_BASE = process.env.API_BASE_URL?.trim() || defaultApiBase();

export function getMikeToken(): string | null {
    try {
        return window.localStorage.getItem(TOKEN_KEY);
    } catch {
        return null;
    }
}

export function setMikeToken(token: string): void {
    try {
        window.localStorage.setItem(TOKEN_KEY, token);
    } catch {
        /* ignore */
    }
}

export function clearMikeToken(): void {
    try {
        window.localStorage.removeItem(TOKEN_KEY);
    } catch {
        /* ignore */
    }
}

export function authHeader(): Record<string, string> {
    const t = getMikeToken();
    return t ? { Authorization: `Bearer ${t}` } : {};
}

/**
 * Broadcast that the stored JWT is no longer accepted by the backend.
 *
 * The Word add-in cannot run an OAuth refresh (Office blocks the
 * popup pattern eulex.ai's PKCE flow needs) — once the JWT expires the
 * user has to re-pair from the Max web app. We surface that via a
 * DOM CustomEvent the root <App/> component listens for; it clears the
 * stored token and flips back to the Login view.
 *
 * Centralising the signal here keeps `api.ts` ignorant of UI state and
 * means a single `apiFetch` wrapper at the HTTP boundary catches every
 * 401 in one place.
 */
export function signalAuthExpired(): void {
    clearMikeToken();
    try {
        window.dispatchEvent(new CustomEvent("mike:auth-expired"));
    } catch {
        /* SSR / non-DOM environments — nothing to dispatch on. */
    }
}

/**
 * `fetch` shim that auto-handles 401 from the backend.
 *
 * All add-in HTTP calls funnel through this. When the backend reports
 * 401 we assume the eulex.ai JWT expired (it has no in-app refresh),
 * fire the "mike:auth-expired" event so the UI can route the user back
 * to Login, then return the response so callers' existing error paths
 * still run (their `chat 401` / `projects 401` thrown errors are useful
 * for log breadcrumbs).
 */
export async function apiFetch(
    input: RequestInfo,
    init?: RequestInit,
): Promise<Response> {
    const res = await fetch(input, init);
    if (res.status === 401) signalAuthExpired();
    return res;
}

/**
 * Redeem a 6-digit pairing code generated by the web frontend's
 * /account/word page. Returns the JWT and stores it in localStorage.
 */
export async function redeemPairingCode(code: string): Promise<string> {
    const trimmed = code.replace(/\s/g, "");
    if (!/^\d{6}$/.test(trimmed)) {
        throw new Error("Code must be 6 digits.");
    }
    const res = await fetch(`${API_BASE}/auth/pair/redeem`, {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            Accept: "application/json",
        },
        body: JSON.stringify({ code: trimmed }),
    });
    if (!res.ok) {
        const text = await res.text().catch(() => "");
        let detail = text;
        try {
            const parsed = JSON.parse(text);
            detail = parsed?.detail ?? text;
        } catch {
            /* keep raw text */
        }
        throw new Error(detail || `pair/redeem ${res.status}`);
    }
    const data = (await res.json()) as { token: string };
    setMikeToken(data.token);
    return data.token;
}

/**
 * Quick token sanity probe: hits a cheap authenticated endpoint to
 * decide if the stored token is still valid. Used on add-in mount to
 * decide whether to show Login or MainLayout.
 */
export async function isTokenValid(): Promise<boolean> {
    const token = getMikeToken();
    if (!token) return false;
    try {
        const res = await fetch(`${API_BASE}/user/profile`, {
            headers: { Authorization: `Bearer ${token}`, Accept: "application/json" },
            cache: "no-store",
        });
        return res.ok;
    } catch {
        return false;
    }
}

export async function logout(): Promise<void> {
    clearMikeToken();
}
